title: Hindsight
author: VladLiss
email: vladimir.lissouba@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm just trying to express myself through photons. There will be some notes about
  books i liked, being a live performer in a virtual era,
  trying to find my space in a virtual landscape.
  

# social links
twitter_username: VladLiss # DO NOT include the @ character, or else the build will fail!
github_username:  VladLiss # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
